version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - poc_rede_social_data:/var/lib/mysql

volumes:
  poc_rede_social_data:

#docker-compose up